import { InvariantCheckResult } from "../codegen/InvariantChecker";
import { SimulationReport } from "../simulation/SimulationReport";
import { PipelineInput } from "../pipeline/UpgradePipeline";

interface GeneratedCode {
  diff: string;
  reasoning: string;
  warnings: string[];
  changedFunctions: string[];
  confidence: number;
}

interface ReportInput {
  input: PipelineInput;
  generated: GeneratedCode;
  invariantResults: InvariantCheckResult[];
  simulationReport: SimulationReport;
  success: boolean;
}

export class ReportGenerator {
  generate(data: ReportInput): string {
    const { input, generated, invariantResults, simulationReport, success } = data;
    const statusEmoji = success ? "✅" : "❌";
    const ts = new Date().toISOString();

    const invariantRows = invariantResults.map(r => {
      const icon = r.verdict === "PASS" ? "✅" : r.verdict === "FAIL" ? "❌" : "⚠️";
      return `| ${r.invariantId} | ${icon} ${r.verdict} | ${r.riskLevel} | ${r.reasoning.substring(0, 100)}... |`;
    }).join("\n");

    const sanityRows = simulationReport.sanityChecks.map(c => {
      const icon = c.passed ? "✅" : "❌";
      return `| ${icon} ${c.name} | ${c.details} |`;
    }).join("\n");

    const stateDiffRows = simulationReport.stateDiffs.map(d =>
      `| \`${d.variable}\` | \`${d.before}\` | \`${d.after}\` |`
    ).join("\n");

    const warningsList = generated.warnings.length > 0
      ? generated.warnings.map(w => `- ⚠️ ${w}`).join("\n")
      : "_None_";

    const compilationWarnings = simulationReport.compilationWarnings.length > 0
      ? simulationReport.compilationWarnings.map(w => `- ${w}`).join("\n")
      : "_None_";

    return `# ProtocolGuard Upgrade Report

**Generated:** ${ts}
**Proposal:** #${input.proposalId} — ${input.title}
**Protocol:** ${input.protocolName} (\`${input.protocolAddress}\`)
**Outcome:** ${statusEmoji} ${success ? "APPROVED FOR EXECUTION" : "REJECTED"}

---

## 1. Proposal Summary

${input.description}

${input.constraints.length > 0 ? `**Additional Constraints:**\n${input.constraints.map(c => `- ${c}`).join("\n")}` : ""}

---

## 2. AI-Generated Changes

**Model:** claude-opus-4-5
**Confidence:** ${generated.confidence}/100
**Changed Functions:** ${generated.changedFunctions.join(", ") || "_none_"}

### Reasoning

${generated.reasoning}

### Diff

\`\`\`diff
${generated.diff}
\`\`\`

### AI Warnings

${warningsList}

---

## 3. Invariant Analysis

| ID | Verdict | Risk | Reasoning |
|----|---------|------|-----------|
${invariantRows || "_No invariants checked_"}

---

## 4. Simulation Results

**Duration:** ${simulationReport.durationMs}ms
**Block:** ${simulationReport.blockNumber}
${simulationReport.failureReason ? `**Failure Reason:** ${simulationReport.failureReason}` : ""}

### Sanity Checks

| Check | Details |
|-------|---------|
${sanityRows || "_No checks run_"}

### State Diffs

| Variable | Before | After |
|----------|--------|-------|
${stateDiffRows || "_No state changes detected_"}

### Compilation Warnings

${compilationWarnings}

---

## 5. Conclusion

${success
  ? `This upgrade passed all automated checks. It is now queued for timelock execution.
    
> **Security Note:** This report was generated by an AI system. Always review changes carefully before execution.`
  : `This upgrade was **rejected** by the automated pipeline.

**Reason:** ${simulationReport.failureReason ?? "See invariant analysis above."}

The upgrade will NOT be executed. The proposer should review the failure reasons and submit a corrected proposal.`
}

---
_This report was automatically generated by ProtocolGuard AI Engine_
`;
  }

  generateHtml(data: ReportInput): string {
    const md = this.generate(data);
    // Simple HTML wrapper for the markdown content
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ProtocolGuard Upgrade Report — Proposal #${data.input.proposalId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; }
    pre { background: #f4f4f4; padding: 1rem; border-radius: 4px; overflow-x: auto; }
    code { background: #f4f4f4; padding: 0.2em 0.4em; border-radius: 3px; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #ddd; padding: 0.5rem 1rem; text-align: left; }
    th { background: #f8f8f8; }
  </style>
</head>
<body>
<pre>${md.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
</body>
</html>`;
  }
}
